#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: register the Spotify developer app for slopify.
# Resolves https://github.com/jnsdls/slopify/issues/4.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO="jnsdls/slopify"
TICKET=4
MAP=2
KEYCHAIN_ITEM="spotify-client-id"
REDIRECT_URI="http://127.0.0.1"
APP_NAME="slopify"

banner "Spotify developer app for slopify"

# ── 1. Preflight ─────────────────────────────────────────────────────────
stage "Preflight"
say "This wizard needs the macOS Keychain (security) and gh, logged in."
command -v security >/dev/null || { warn "security not found; this wizard is macOS only"; exit 1; }
if ! gh auth status >/dev/null 2>&1; then
  warn "gh is not logged in. Run 'gh auth login' first, then re-run this wizard."
  exit 1
fi
if security find-generic-password -s "$KEYCHAIN_ITEM" -w >/dev/null 2>&1; then
  note "Keychain already has $KEYCHAIN_ITEM. You can keep it or overwrite it in stage 3."
fi
say "You need to be logged in at developer.spotify.com with the Premium account that owns the app."
say "Development mode only works while the owner holds Premium."
pause "Ready?"

# ── 2. Create the app ────────────────────────────────────────────────────
stage "Create the app"
open_url "https://developer.spotify.com/dashboard"
step "Click 'Create app'."
step "App name: $APP_NAME"
step "App description: anything short, e.g. 'Personal menu-bar Spotify player.'"
step "Website: leave blank."
step "Redirect URIs: $REDIRECT_URI   (loopback IP, no port, no path; localhost is rejected)"
step "If the form asks which APIs/SDKs you plan to use, tick 'Web API' and 'Web Playback SDK'."
step "Accept the developer terms, then click 'Save'."
note "Some dashboard versions ask only name and description at creation. If so, add the"
note "redirect URI afterwards under Settings, then 'Basic Information', and save."
pause "Done?"

# ── 3. Capture the client id ─────────────────────────────────────────────
stage "Client id"
step "On the app page, open 'Settings'. The Client ID is at the top of 'Basic Information'."
step "Copy it. It's a 32-character hex string."
note "Skip the client secret. slopify uses PKCE and never needs it. Don't store it anywhere."
while :; do
  ask SPOTIFY_CLIENT_ID "Paste the Client ID:"
  [[ "$SPOTIFY_CLIENT_ID" =~ ^[0-9a-f]{32}$ ]] && break
  warn "That doesn't look like a Spotify client id (32 lowercase hex chars). Try again."
done
security add-generic-password -a "$USER" -s "$KEYCHAIN_ITEM" -U -T /usr/bin/security -w "$SPOTIFY_CLIENT_ID"
printf '  %s✓ stored%s Keychain item %s\n' "$GREEN" "$RESET" "$KEYCHAIN_ITEM"
note "Read it back any time with: security find-generic-password -s $KEYCHAIN_ITEM -w"
pause

# ── 4. Confirm the redirect URI ──────────────────────────────────────────
stage "Redirect URI"
step "Still in Settings, check 'Redirect URIs' lists exactly: $REDIRECT_URI"
step "If it's missing or has a port, fix it and click 'Save'."
note "The app picks a free port at auth time and sends it in the request; Spotify allows that only"
note "for a loopback IP registered without a port."
if ! confirm "Does the dashboard show $REDIRECT_URI as the only redirect URI?"; then
  warn "Fix it before continuing, otherwise the loopback login will fail with invalid_redirect_uri."
  pause "Fixed?"
fi

# ── 5. Allowlist listeners ───────────────────────────────────────────────
stage "Allowlisted listeners"
say "Development mode allows 5 users. The owner counts as one. Non-allowlisted accounts get 403s."
step "In Settings, open the 'User Management' tab."
step "For each listener: click 'Add new user', enter their name and the email on their Spotify account, save."
step "Each listener needs Premium too, since the Web Playback SDK and player endpoints are Premium-only."
note "You can add or remove people later. Don't paste their emails here; the count is enough."
while :; do
  ask LISTENER_COUNT "How many listeners did you add (not counting yourself)? [0-4]"
  [[ "$LISTENER_COUNT" =~ ^[0-4]$ ]] && break
  warn "Enter a number from 0 to 4."
done

# ── 6. Record the resolution on the tracker ──────────────────────────────
stage "Record on GitHub"
RESOLUTION=$(cat <<MD
## Resolution

Registered via \`scripts/register-spotify-app.sh\`.

- App name: \`$APP_NAME\`, created on the owner's Premium account, development mode.
- Client id: \`$SPOTIFY_CLIENT_ID\` (public; fine to hard-code in the app).
- Redirect URI registered: \`$REDIRECT_URI\`. Loopback IP, no port. The app appends its ephemeral port at auth time.
- Client secret: not stored anywhere. PKCE flow doesn't use it.
- Keychain: the client id is also in the macOS Keychain as \`$KEYCHAIN_ITEM\` (read with \`security find-generic-password -s $KEYCHAIN_ITEM -w\`).
- Allowlisted listeners besides the owner: $LISTENER_COUNT of 4 slots used. Managed under Settings, User Management, in the dashboard.
MD
)
MAP_LINE="- [Register the Spotify developer app](https://github.com/$REPO/issues/$TICKET): app \`$APP_NAME\` registered in dev mode, client id \`$SPOTIFY_CLIENT_ID\` (also in Keychain as \`$KEYCHAIN_ITEM\`), redirect \`$REDIRECT_URI\` with no port, no client secret kept, $LISTENER_COUNT listeners allowlisted besides the owner."
say "About to post this to issue #$TICKET, close it, and add a line to the map (#$MAP):"
printf '\n%s\n\n%s\n\n' "$RESOLUTION" "$MAP_LINE"
if confirm "Post, close, and update the map?"; then
  gh issue comment "$TICKET" --repo "$REPO" --body "$RESOLUTION" >/dev/null
  gh issue close "$TICKET" --repo "$REPO" >/dev/null
  printf '  %s✓ resolved%s issue #%s\n' "$GREEN" "$RESET" "$TICKET"
  body=$(gh issue view "$MAP" --repo "$REPO" --json body --jq .body)
  if printf '%s' "$body" | grep -q "^## Not yet specified"; then
    newbody=$(printf '%s\n' "$body" | awk -v line="$MAP_LINE" '
      /^## Not yet specified/ { print line; print ""; }
      { print }')
    gh issue edit "$MAP" --repo "$REPO" --body "$newbody" >/dev/null
    printf '  %s✓ appended%s decision to map #%s\n' "$GREEN" "$RESET" "$MAP"
  else
    SKIPPED+=("map #$MAP: add this line under Decisions so far: $MAP_LINE")
    warn "couldn't find the map's 'Not yet specified' heading; add the decision line by hand"
  fi
else
  SKIPPED+=("post resolution to issue #$TICKET and close it")
  SKIPPED+=("append to map #$MAP under Decisions so far: $MAP_LINE")
fi

finish
say "Next on the map: the castLabs spike (issue #3) is now unblocked."
printf '\n'
